config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "gardens#index"

  resources :gardens do
    resources :plants, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])
    @plant = Plant.new
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(garde_params)
    if @garden.save
      redirect_to gardens_path
    else
      render :new
    end
  end

  private

  def garde_params
    params.require(:garden).permit(:name, :image_url)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render "gardens/show", status: :unprocessable_entity
    end
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/index.html.erb
<div class="container">
  <h1>Gardens</h1>

  <h3><%= link_to "add Garde", new_garden_path %></h3>

  <% @gardens.each do |garden| %>
    <p><%= garden.name %></p>
    <p><%= garden.image_url %></p>
    <%= link_to "ver detalle", garden_path(garden) %>
  <% end %>
</div>

app/views/gardens/new.html.erb
<div class="container">
  <%= simple_form_for @garden do |f| %>
    <%= f.input :name %>
    <%= f.input :image_url %>
    <%= f.submit class: "btn btn-success mt-2" %>
  <% end %>
</div>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.image_url %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>
<div>

<div class="container">
  <div class="row mt-5">
    <% @garden.plants.each do |plant| %>
      <div class="col-4 mb-5">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url %>)">
          <%= plant.name %>
        </div>
      </div>
    <% end %>
  </div>
</div>



<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <%= simple_form_for [@garden, @plant] do |f| %>
        <%= f.input :name %>
        <%= f.input :image_url %>
        <%= f.submit class: "btn btn-warning mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>